// apps/web/.backup-cleanup/App-react.jsx
import React, { useState, useEffect, useCallback, useRef } from 'react'
import { Layout, Menu, Space, Button, Tag, Switch, Modal, message, Spin } from 'antd'
import { useNavigate, useLocation, Outlet } from 'react-router-dom'
import {
  DashboardOutlined,
  UnorderedListOutlined,
  SettingOutlined,
  FileTextOutlined,
  LineChartOutlined,
  DatabaseOutlined,
  ApiOutlined,
  EyeOutlined,
  FundOutlined,
  AreaChartOutlined,
  BarChartOutlined,
  LinkOutlined,
  MoonOutlined,
  SunOutlined
} from '@ant-design/icons'
import { useSystemStore } from './stores/systemStore'
import { startSystem, stopSystem, restartSystem } from './api/system'
import { storage, STORAGE_KEYS } from './utils/storage'
import ErrorMonitor from './components/react/ErrorMonitor'
import PageTransition from './components/react/PageTransition'
import backendStatus from './utils/backendStatus'
import './styles/app-react.scss'

const { Header, Sider, Content } = Layout

// 菜单项配置
const menuItems = [
  {
    key: '/',
    icon: <DashboardOutlined />,
    label: '监控仪表板'
  },
  {
    key: '/events',
    icon: <UnorderedListOutlined />,
    label: '事件监控'
  },
  {
    key: '/config',
    icon: <SettingOutlined />,
    label: '系统配置'
  },
  {
    key: '/logs',
    icon: <FileTextOutlined />,
    label: '日志查看'
  },
  {
    key: '/trading',
    icon: <LineChartOutlined />,
    label: '策略回测'
  },
  {
    key: '/data',
    icon: <DatabaseOutlined />,
    label: '数据管理'
  },
  {
    key: '/data-source',
    icon: <ApiOutlined />,
    label: '数据源配置'
  },
  {
    key: '/data-source-monitor',
    icon: <EyeOutlined />,
    label: '数据源监控'
  },
  {
    key: '/market',
    icon: <FundOutlined />,
    label: '市场数据'
  },
  {
    key: '/market-overview',
    icon: <AreaChartOutlined />,
    label: '市场总貌'
  },
  {
    key: '/pro-trading',
    icon: <BarChartOutlined />,
    label: '市场行情'
  },
  {
    key: '/workers-proxy',
    icon: <LinkOutlined />,
    label: 'Workers 代理'
  }
]

// 页面标题映射
const pageTitles = {
  '/': '监控仪表板',
  '/events': '事件监控',
  '/config': '系统配置',
  '/logs': '日志查看',
  '/trading': '策略回测',
  '/pro-trading': '市场行情',
  '/market': '市场数据',
  '/market-overview': '市场总貌',
  '/data': '数据管理',
  '/data-source': '数据源监控',
  '/data-source-monitor': '数据源监控',
  '/workers-proxy': 'Workers 代理'
}

// 调试日志工具
const debugLog = (stage, message, data = null) => {
  const timestamp = new Date().toISOString()
  const logEntry = `[App-react.jsx ${timestamp}] ${stage}: ${message}`
  console.log('%c' + logEntry, 'color: #1890ff; font-weight: bold;', data)
}

function App() {
  const navigate = useNavigate()
  const location = useLocation()
  const systemStore = useSystemStore()

  // 状态
  const [collapsed, setCollapsed] = useState(false)
  const [isDark, setIsDark] = useState(false)
  const [systemLoading, setSystemLoading] = useState(false)
  const [loading, setLoading] = useState(true)
  const [pauseStatusPolling, setPauseStatusPolling] = useState(false)

  // Refs
  const statusTimerRef = useRef(null)

  // 计算属性
  const activeMenu = location.pathname
  const pageTitle = pageTitles[location.pathname] || 'DeepSearch'

  const systemStatus = (() => {
    try {
      if (systemStore.status?.engine?.running) {
        return { type: 'success', text: '系统运行中', running: true }
      }
    } catch (e) {
      console.warn('获取系统状态失败:', e)
    }
    return { type: 'default', text: '系统已停止', running: false }
  })()

  // 切换主题
  const toggleTheme = useCallback((checked) => {
    setIsDark(checked)
    if (checked) {
      document.documentElement.classList.add('dark')
      storage.setItem(STORAGE_KEYS.THEME, 'dark')
    } else {
      document.documentElement.classList.remove('dark')
      storage.setItem(STORAGE_KEYS.THEME, 'light')
    }
  }, [])

  // 启动系统
  const handleSystemStart = useCallback(async () => {
    if (!backendStatus.isAvailable) {
      message.error('后端服务不可用，请先启动后端服务')
      return
    }

    try {
      setSystemLoading(true)
      setPauseStatusPolling(true)
      const result = await startSystem()
      message.success(result.message || '系统启动成功')
      setTimeout(() => {
        setPauseStatusPolling(false)
        systemStore.fetchStatus()
      }, 1000)
    } catch (error) {
      message.error(error.message || '系统启动失败')
      setPauseStatusPolling(false)
    } finally {
      setSystemLoading(false)
    }
  }, [systemStore])

  // 停止系统
  const handleSystemStop = useCallback(async () => {
    if (!backendStatus.isAvailable) {
      message.error('后端服务不可用')
      return
    }

    Modal.confirm({
      title: '停止交易引擎',
      content: '确定要停止交易引擎吗？这将停止所有交易活动，但WebUI仍会继续运行。',
      okText: '确定',
      cancelText: '取消',
      type: 'warning',
      onOk: async () => {
        try {
          setSystemLoading(true)
          setPauseStatusPolling(true)
          const result = await stopSystem()
          message.success(result.message || '交易引擎已停止')
          setTimeout(() => {
            setPauseStatusPolling(false)
            systemStore.fetchStatus()
          }, 1000)
        } catch (error) {
          message.error(error.message || '系统停止失败')
          setPauseStatusPolling(false)
        } finally {
          setSystemLoading(false)
        }
      }
    })
  }, [systemStore])

  // 重启系统
  const handleSystemRestart = useCallback(async () => {
    if (!backendStatus.isAvailable) {
      message.error('后端服务不可用')
      return
    }

    Modal.confirm({
      title: '重启交易引擎',
      content: '确定要重启交易引擎吗？这将中断当前所有交易活动并重新启动。',
      okText: '确定',
      cancelText: '取消',
      type: 'warning',
      onOk: async () => {
        try {
          setSystemLoading(true)
          setPauseStatusPolling(true)
          const result = await restartSystem()
          message.success(result.message || '交易引擎重启成功')
          setTimeout(() => {
            setPauseStatusPolling(false)
            systemStore.fetchStatus()
          }, 2000)
        } catch (error) {
          message.error(error.message || '系统重启失败')
          setPauseStatusPolling(false)
        } finally {
          setSystemLoading(false)
        }
      }
    })
  }, [systemStore])

  // 菜单点击处理
  const handleMenuClick = useCallback(({ key }) => {
    navigate(key)
  }, [navigate])

  // 后端状态变化处理
  const handleBackendStatusChange = useCallback((available) => {
    debugLog('BACKEND', `Backend status changed: ${available ? 'available' : 'unavailable'}`)

    if (available && !pauseStatusPolling && !systemLoading) {
      systemStore.fetchStatus().catch(err => {
        debugLog('API', 'Status fetch failed after backend recovery', { error: err.message })
      })
    }
  }, [pauseStatusPolling, systemLoading, systemStore])

  // 初始化
  useEffect(() => {
    debugLog('LIFECYCLE', 'Component mounting')
    const mountStartTime = Date.now()

    const init = async () => {
      try {
        // 初始化主题
        debugLog('THEME', '初始化主题', { isDark })
        document.documentElement.classList.remove('dark')

        // 检查后端状态
        debugLog('API', '检查后端状态')
        const isBackendAvailable = await backendStatus.checkStatus()

        if (isBackendAvailable) {
          debugLog('API', '开始获取系统状态')
          const fetchStartTime = Date.now()

          try {
            await systemStore.fetchStatus()
            const fetchDuration = Date.now() - fetchStartTime
            debugLog('API', '系统状态获取成功', {
              duration: `${fetchDuration}ms`,
              status: systemStore.status
            })
          } catch (fetchError) {
            const fetchDuration = Date.now() - fetchStartTime
            debugLog('API', '系统状态获取失败', {
              duration: `${fetchDuration}ms`,
              error: fetchError.message
            })
            throw fetchError
          }
        } else {
          debugLog('API', '后端不可用，跳过状态获取')
        }

        // 延迟关闭loading
        setTimeout(() => {
          setLoading(false)
          debugLog('LOADING', 'Loading关闭成功')
        }, 300)

        const mountDuration = Date.now() - mountStartTime
        debugLog('LIFECYCLE', 'Component mounted', { totalDuration: `${mountDuration}ms` })

      } catch (err) {
        const mountDuration = Date.now() - mountStartTime
        debugLog('ERROR', 'Initialization error', {
          duration: `${mountDuration}ms`,
          error: err.message
        })
        console.warn('获取系统状态失败，将使用默认值:', err)
        setLoading(false)
      }
    }

    init()

    // 监听后端状态变化
    backendStatus.addListener(handleBackendStatusChange)

    // 启动状态轮询
    debugLog('POLLING', '启动状态轮询定时器', { interval: '5000ms' })
    statusTimerRef.current = setInterval(async () => {
      if (!pauseStatusPolling && !systemLoading && backendStatus.isAvailable) {
        debugLog('POLLING', '执行状态轮询')
        systemStore.fetchStatus().catch(err => {
          if (!systemLoading) {
            debugLog('POLLING', '状态轮询失败', { error: err.message })
            console.warn('更新系统状态失败:', err)
          }
        })
      }
    }, 5000)

    // 清理函数
    return () => {
      if (statusTimerRef.current) {
        clearInterval(statusTimerRef.current)
        statusTimerRef.current = null
      }
      backendStatus.removeListener(handleBackendStatusChange)
      debugLog('LIFECYCLE', 'Component unmounted - cleaned up resources')
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  if (loading) {
    return (
      <div className="app-loading">
        <Spin size="large" tip="正在初始化 DeepSearch 系统..." />
      </div>
    )
  }

  return (
    <Layout className="app-layout">
      <Sider
        width={200}
        className="app-sider"
        collapsed={collapsed}
        onCollapse={setCollapsed}
      >
        <div className="logo">
          <h2>DeepSearch</h2>
        </div>
        <Menu
          theme="light"
          mode="inline"
          selectedKeys={[activeMenu]}
          items={menuItems}
          onClick={handleMenuClick}
        />
      </Sider>

      <Layout>
        <Header className="app-header">
          <div className="header-left">
            <h3>{pageTitle}</h3>
          </div>
          <div className="header-right">
            <Space size="middle">
              {/* 系统状态指示器 */}
              <div className="system-status">
                <Tag color={systemStatus.type}>
                  <span className={systemStatus.running ? 'breathing status-indicator' : 'status-indicator'}>
                    ●
                  </span>
                  {systemStatus.text}
                </Tag>
              </div>

              {/* 系统控制按钮 */}
              <Space.Compact>
                {!systemStatus.running ? (
                  <Button
                    type="primary"
                    size="small"
                    loading={systemLoading}
                    onClick={handleSystemStart}
                  >
                    启动引擎
                  </Button>
                ) : (
                  <>
                    <Button
                      danger
                      size="small"
                      loading={systemLoading}
                      onClick={handleSystemStop}
                    >
                      停止引擎
                    </Button>
                    <Button
                      type="default"
                      size="small"
                      loading={systemLoading}
                      onClick={handleSystemRestart}
                    >
                      重启引擎
                    </Button>
                  </>
                )}
              </Space.Compact>

              {/* 主题切换 */}
              <Switch
                checked={isDark}
                onChange={toggleTheme}
                checkedChildren={<MoonOutlined />}
                unCheckedChildren={<SunOutlined />}
              />
            </Space>
          </div>
        </Header>

        <Content className="app-content">
          <PageTransition>
            <Outlet />
          </PageTransition>
        </Content>
      </Layout>

      {/* 错误监控组件 */}
      <ErrorMonitor />
    </Layout>
  )
}

export default App

// deepsearch/webui/frontend/src/App.vue
<template>
  <el-config-provider :locale="zhCn">
    <div id="app">
      <el-container class="layout-container">
        <!-- 侧边栏 -->
        <el-aside class="layout-aside" width="200px">
          <div class="logo">
            <h2>DeepSearch</h2>
          </div>
          <el-menu
              :default-active="activeMenu"
              active-text-color="#409eff"
              background-color="#304156"
              class="el-menu-vertical"
              router
              text-color="#bfcbd9"
          >
            <el-menu-item index="/">
              <el-icon>
                <Monitor/>
              </el-icon>
              <span>监控仪表板</span>
            </el-menu-item>
            <el-menu-item index="/events">
              <el-icon>
                <List/>
              </el-icon>
              <span>事件监控</span>
            </el-menu-item>
            <el-menu-item index="/config">
              <el-icon>
                <Setting/>
              </el-icon>
              <span>系统配置</span>
            </el-menu-item>
            <el-menu-item index="/logs">
              <el-icon>
                <Document/>
              </el-icon>
              <span>日志查看</span>
            </el-menu-item>
            <el-menu-item index="/trading">
              <el-icon>
                <TrendCharts/>
              </el-icon>
              <span>交易监控</span>
            </el-menu-item>
            <el-menu-item index="/strategy">
              <el-icon>
                <Aim/>
              </el-icon>
              <span>策略管理</span>
            </el-menu-item>
            <el-menu-item index="/data">
              <el-icon>
                <DataAnalysis/>
              </el-icon>
              <span>数据管理</span>
            </el-menu-item>
            <el-menu-item index="/data-source">
              <el-icon>
                <Connection/>
              </el-icon>
              <span>数据源监控</span>
            </el-menu-item>
            <el-menu-item index="/market">
              <el-icon>
                <TrendCharts/>
              </el-icon>
              <span>市场数据</span>
            </el-menu-item>
            <el-menu-item index="/pro-trading">
              <el-icon>
                <DataLine/>
              </el-icon>
              <span>市场行情</span>
            </el-menu-item>
            <el-menu-item index="/workers-proxy">
              <el-icon>
                <Link/>
              </el-icon>
              <span>Workers 代理</span>
            </el-menu-item>
          </el-menu>
        </el-aside>

        <!-- 主内容区 -->
        <el-container>
          <!-- 顶部栏 -->
          <el-header class="layout-header">
            <div class="header-left">
              <h3>{{ pageTitle }}</h3>
            </div>
            <div class="header-right">
              <el-space>
                <!-- 系统状态指示器 -->
                <div class="system-status">
                  <el-tag :type="systemStatus.type" effect="dark">
                    <span :class="{ 'breathing': systemStatus.running }" class="status-indicator">●</span>
                    {{ systemStatus.text }}
                  </el-tag>
                </div>

                <!-- 系统控制按钮 -->
                <el-button-group>
                  <el-button
                      v-if="!systemStatus.running"
                      :loading="systemLoading"
                      size="small"
                      type="success"
                      @click="handleSystemStart"
                  >
                    启动引擎
                  </el-button>
                  <el-button
                      v-else
                      :loading="systemLoading"
                      size="small"
                      type="danger"
                      @click="handleSystemStop"
                  >
                    停止引擎
                  </el-button>
                  <el-button
                      v-if="systemStatus.running"
                      :loading="systemLoading"
                      size="small"
                      type="warning"
                      @click="handleSystemRestart"
                  >
                    重启引擎
                  </el-button>
                </el-button-group>

                <!-- 主题切换 -->
                <el-switch
                    v-model="isDark"
                    :active-icon="Moon"
                    :inactive-icon="Sunny"
                    inline-prompt
                    @change="toggleTheme"
                />
              </el-space>
            </div>
          </el-header>

          <!-- 页面内容 -->
          <el-main class="layout-main">
            <router-view v-slot="{ Component }">
              <transition mode="out-in" name="fade">
                <component :is="Component"/>
              </transition>
            </router-view>
          </el-main>
        </el-container>
      </el-container>

      <!-- 错误监控组件 -->
      <ErrorMonitor/>
    </div>
  </el-config-provider>
</template>

<script setup>
import {computed, onBeforeMount, onMounted, onUnmounted, ref} from 'vue'
import {useRoute} from 'vue-router'
import {ElLoading, ElMessage, ElMessageBox} from 'element-plus'
import {
  Aim,
  Connection,
  DataAnalysis,
  DataLine,
  Document,
  Link,
  List,
  Monitor,
  Moon,
  Setting,
  Sunny,
  TrendCharts
} from '@element-plus/icons-vue'
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'
import {useSystemStore} from '@/stores/system'
import {restartSystem, startSystem, stopSystem} from '@/api/system'
import {storage, STORAGE_KEYS} from '@/utils/storage'
import ErrorMonitor from '@/components/ErrorMonitor.vue'
import backendStatus from '@/utils/backendStatus'

// 定义组件名称
defineOptions({
  name: 'App'
})

const route = useRoute()
const systemStore = useSystemStore()

// 当前激活的菜单
const activeMenu = computed(() => route.path)

// 页面标题
const pageTitle = computed(() => {
  const titles = {
    '/': '监控仪表板',
    '/events': '事件监控',
    '/config': '系统配置',
    '/logs': '日志查看',
    '/trading': '交易监控',
    '/pro-trading': '市场行情',
    '/market': '市场数据',
    '/data': '数据管理',
    '/data-source': '数据源监控',
    '/workers-proxy': 'Workers 代理'
  }
  return titles[route.path] || 'DeepSearch'
})

// 系统状态
const systemStatus = computed(() => {
  try {
    if (systemStore.status?.engine?.running) {
      return {type: 'success', text: '系统运行中', running: true}
    }
  } catch (e) {
    console.warn('获取系统状态失败:', e)
  }
  return {type: 'info', text: '系统已停止', running: false}
})

// 系统操作加载状态
const systemLoading = ref(false)

// 是否暂停状态轮询
const pauseStatusPolling = ref(false)

// 暗色主题 - 使用安全的 storage
const isDark = ref(storage.getItem(STORAGE_KEYS.THEME) === 'dark')

// 切换主题
const toggleTheme = (value) => {
  if (value) {
    document.documentElement.classList.add('dark')
    storage.setItem(STORAGE_KEYS.THEME, 'dark')
  } else {
    document.documentElement.classList.remove('dark')
    storage.setItem(STORAGE_KEYS.THEME, 'light')
  }
}

// 启动系统
const handleSystemStart = async () => {
  // 检查后端是否可用
  if (!backendStatus.isAvailable) {
    ElMessage.error('后端服务不可用，请先启动后端服务')
    return
  }
  
  try {
    systemLoading.value = true
    pauseStatusPolling.value = true  // 暂停轮询
    const result = await startSystem()
    ElMessage.success(result.message || '系统启动成功')
    // 延迟一下再恢复轮询
    setTimeout(() => {
      pauseStatusPolling.value = false
      systemStore.fetchStatus()
    }, 1000)
  } catch (error) {
    ElMessage.error(error.message || '系统启动失败')
    pauseStatusPolling.value = false  // 失败时恢复轮询
  } finally {
    systemLoading.value = false
  }
}

// 停止系统
const handleSystemStop = async () => {
  // 检查后端是否可用
  if (!backendStatus.isAvailable) {
    ElMessage.error('后端服务不可用')
    return
  }
  
  try {
    await ElMessageBox.confirm(
        '确定要停止交易引擎吗？这将停止所有交易活动，但WebUI仍会继续运行。',
        '停止交易引擎',
        {
          confirmButtonText: '确定',
          cancelButtonText: '取消',
          type: 'warning',
        }
    )

    systemLoading.value = true
    pauseStatusPolling.value = true  // 暂停轮询
    const result = await stopSystem()
    ElMessage.success(result.message || '交易引擎已停止')
    // 延迟一下再恢复轮询
    setTimeout(() => {
      pauseStatusPolling.value = false
      systemStore.fetchStatus()
    }, 1000)
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(error.message || '系统停止失败')
    }
    pauseStatusPolling.value = false  // 失败时恢复轮询
  } finally {
    systemLoading.value = false
  }
}

// 重启系统
const handleSystemRestart = async () => {
  // 检查后端是否可用
  if (!backendStatus.isAvailable) {
    ElMessage.error('后端服务不可用')
    return
  }
  
  try {
    await ElMessageBox.confirm(
        '确定要重启交易引擎吗？这将中断当前所有交易活动并重新启动。',
        '重启交易引擎',
        {
          confirmButtonText: '确定',
          cancelButtonText: '取消',
          type: 'warning',
        }
    )

    systemLoading.value = true
    pauseStatusPolling.value = true  // 暂停轮询
    const result = await restartSystem()
    ElMessage.success(result.message || '交易引擎重启成功')
    // 延迟一下再恢复轮询
    setTimeout(() => {
      pauseStatusPolling.value = false
      systemStore.fetchStatus()
    }, 2000)  // 重启需要更长时间
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(error.message || '系统重启失败')
    }
    pauseStatusPolling.value = false  // 失败时恢复轮询
  } finally {
    systemLoading.value = false
  }
}

// 定时获取系统状态
let statusTimer = null

// 后端状态监听
const handleBackendStatusChange = (available) => {
  debugLog('BACKEND', `Backend status changed: ${available ? 'available' : 'unavailable'}`)

  if (available) {
    // 后端恢复，立即获取状态
    if (!pauseStatusPolling.value && !systemLoading.value) {
      systemStore.fetchStatus().catch(err => {
        debugLog('API', 'Status fetch failed after backend recovery', {error: err.message})
      })
    }
  }
}

// 调试日志工具
const debugLog = (stage, message, data = null) => {
  const timestamp = new Date().toISOString()
  const logEntry = `[App.vue ${timestamp}] ${stage}: ${message}`
  console.log('%c' + logEntry, 'color: #409eff; font-weight: bold;', data)
}

// 在组件挂载前显示全屏loading
debugLog('INIT', '创建全屏Loading')
const loading = ElLoading.service({
  lock: true,
  text: '正在初始化 DeepSearch 系统...',
  background: 'rgba(0, 0, 0, 0.7)',
  customClass: 'deepsearch-loading'
})

// 添加Loading超时保护 - 增加超时时间到15秒
const loadingTimeout = setTimeout(() => {
  debugLog('ERROR', 'Loading超时，强制关闭', {timeout: '15秒'})
  if (loading) {
    loading.close()
    ElMessage.warning('系统初始化较慢，已自动关闭Loading。如有问题请检查后端服务状态。')
  }
}, 15000)

// 组件挂载前
onBeforeMount(() => {
  debugLog('LIFECYCLE', 'onBeforeMount执行')
})

onMounted(async () => {
  debugLog('LIFECYCLE', 'onMounted开始执行')
  const mountStartTime = Date.now()
  
  try {
    // 初始化主题
    debugLog('THEME', '初始化主题', {isDark: isDark.value})
    if (isDark.value) {
      document.documentElement.classList.add('dark')
    }

    // 检查后端状态
    debugLog('API', '检查后端状态')
    const isBackendAvailable = await backendStatus.checkStatus()

    if (isBackendAvailable) {
      // 获取系统状态
      debugLog('API', '开始获取系统状态')
      const fetchStartTime = Date.now()

      try {
        await systemStore.fetchStatus()
        const fetchDuration = Date.now() - fetchStartTime
        debugLog('API', '系统状态获取成功', {
          duration: `${fetchDuration}ms`,
          status: systemStore.status
        })
      } catch (fetchError) {
        const fetchDuration = Date.now() - fetchStartTime
        debugLog('API', '系统状态获取失败', {
          duration: `${fetchDuration}ms`,
          error: fetchError.message,
          stack: fetchError.stack
        })
        throw fetchError
      }
    } else {
      debugLog('API', '后端不可用，跳过状态获取')
    }

    // 延迟一点关闭loading，确保界面渲染完成
    debugLog('LOADING', '准备关闭Loading，延迟300ms')
    setTimeout(() => {
      if (loading) {
        debugLog('LOADING', 'Loading关闭成功')
        loading.close()
        clearTimeout(loadingTimeout) // 清除超时计时器
      }
    }, 300)

    const mountDuration = Date.now() - mountStartTime
    debugLog('LIFECYCLE', 'onMounted执行完成', {totalDuration: `${mountDuration}ms`})
    
  } catch (err) {
    const mountDuration = Date.now() - mountStartTime
    debugLog('ERROR', 'onMounted执行出错', {
      duration: `${mountDuration}ms`,
      error: err.message,
      stack: err.stack
    })
    console.warn('获取系统状态失败，将使用默认值:', err)

    // 确保Loading被关闭
    if (loading) {
      debugLog('LOADING', '错误状态下关闭Loading')
      loading.close()
      clearTimeout(loadingTimeout)
    }
  }

  // 监听后端状态变化
  backendStatus.addListener(handleBackendStatusChange)

  // 启动状态轮询
  debugLog('POLLING', '启动状态轮询定时器', {interval: '5000ms'})
  statusTimer = setInterval(async () => {
    // 如果正在进行系统操作，跳过轮询
    if (!pauseStatusPolling.value && !systemLoading.value) {
      // 先检查后端是否可用
      if (backendStatus.isAvailable) {
        debugLog('POLLING', '执行状态轮询')
        systemStore.fetchStatus().catch(err => {
          // 只在非系统操作期间才显示警告
          if (!systemLoading.value) {
            debugLog('POLLING', '状态轮询失败', {error: err.message})
            console.warn('更新系统状态失败:', err)
          }
        })
      } else {
        debugLog('POLLING', '后端不可用，跳过状态轮询')
      }
    } else {
      debugLog('POLLING', '跳过状态轮询', {
        pauseStatusPolling: pauseStatusPolling.value,
        systemLoading: systemLoading.value
      })
    }
  }, 5000) // 每5秒更新一次
})

// 组件更新时
onUpdated(() => {
  debugLog('LIFECYCLE', 'onUpdated执行', {route: route.path})
})

onUnmounted(() => {
  // 清除状态轮询定时器
  if (statusTimer) {
    clearInterval(statusTimer)
    statusTimer = null
  }

  // 移除后端状态监听器
  backendStatus.removeListener(handleBackendStatusChange)

  debugLog('LIFECYCLE', 'onUnmounted - cleaned up resources')
})
</script>

<style lang="scss">
@use '@/assets/styles/design-tokens.scss' as tokens;

/* 布局容器 */
.layout-container {
  height: 100vh;
  background: var(--bg-color);
}

/* 侧边栏 - 增强版玻璃态 */
.layout-aside {
  @include tokens.dark-glassmorphism(0.8, 20px);
  background: linear-gradient(
          180deg,
          rgba(tokens.$neutral-800, 0.95) 0%,
          rgba(tokens.$neutral-900, 0.98) 100%
  );
  box-shadow: tokens.$shadow-layered;
  transition: all tokens.$duration-base tokens.$ease-out;
  position: relative;
  overflow: hidden;
  border-right: 1px solid rgba(255, 255, 255, 0.1);

  // 渐变光效背景
  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: radial-gradient(circle at 20% 20%, rgba(tokens.$brand-primary, 0.15) 0%, transparent 40%),
    radial-gradient(circle at 80% 80%, rgba(tokens.$brand-secondary, 0.15) 0%, transparent 40%),
    radial-gradient(circle at 50% 50%, rgba(tokens.$brand-accent, 0.08) 0%, transparent 60%);
    pointer-events: none;
    animation: gradientShift 20s ease infinite;
  }

  @keyframes gradientShift {
    0%, 100% {
      opacity: 0.8;
    }
    50% {
      opacity: 1;
    }
  }

  .logo {
    height: 72px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: rgba(0, 0, 0, 0.3);
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    position: relative;
    overflow: hidden;

    &::before {
      content: '';
      position: absolute;
      top: 0;
      left: -100%;
      width: 100%;
      height: 100%;
      background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
      animation: shimmer 3s infinite;
    }

    &::after {
      content: '';
      position: absolute;
      bottom: 0;
      left: 50%;
      transform: translateX(-50%);
      width: 60%;
      height: 1px;
      background: linear-gradient(90deg, transparent, tokens.$brand-primary, transparent);
    }

    h2 {
      color: white;
      font-size: tokens.$font-size-2xl;
      font-weight: tokens.$font-weight-bold;
      letter-spacing: 1px;
      text-shadow: 0 2px 8px rgba(0, 0, 0, 0.4);
      z-index: 1;
      display: flex;
      align-items: center;
      gap: tokens.$spacing-2;

      &::before {
        content: '⚇';
        font-size: 28px;
        @include tokens.gradient-text(tokens.$brand-primary, tokens.$brand-secondary);
      }
    }
  }

  .el-menu {
    border-right: none;
    background: transparent;
    height: calc(100% - 72px);
    padding: tokens.$spacing-2 0;

    .el-menu-item {
      color: rgba(255, 255, 255, 0.7);
      transition: all tokens.$duration-base tokens.$ease-out;
      position: relative;
      margin: tokens.$spacing-1 tokens.$spacing-2;
      border-radius: tokens.$radius-base;
      height: 48px;
      line-height: 48px;
      overflow: hidden;

      // 光晕扩散背景
      &::before {
        content: '';
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translateY(-50%);
        width: 4px;
        height: 0;
        background: tokens.$brand-primary;
        border-radius: tokens.$radius-sm;
        transition: height tokens.$duration-base tokens.$ease-out;
      }

      &::after {
        content: '';
        position: absolute;
        inset: 0;
        background: linear-gradient(90deg, rgba(tokens.$brand-primary, 0.15), transparent);
        opacity: 0;
        transition: opacity tokens.$duration-base;
        border-radius: tokens.$radius-base;
      }

      &:hover {
        color: white;
        transform: translateX(4px);
        
        &::after {
          opacity: 1;
        }

        .el-icon {
          transform: scale(1.1);
          filter: drop-shadow(0 0 8px rgba(tokens.$brand-primary, 0.5));
        }
      }

      &.is-active {
        color: white;
        background: linear-gradient(
                90deg,
                rgba(tokens.$brand-primary, 0.25) 0%,
                rgba(tokens.$brand-primary, 0.1) 100%
        );
        font-weight: tokens.$font-weight-medium;
        @include tokens.inner-glow(tokens.$brand-primary, 8px);
        border: 1px solid rgba(tokens.$brand-primary, 0.3);

        &::before {
          height: 24px;
          width: 3px;
          left: 0;
          background: tokens.$brand-primary;
          box-shadow: 0 0 10px tokens.$brand-primary;
        }

        .el-icon {
          color: tokens.$brand-primary;
          filter: drop-shadow(0 0 10px tokens.$brand-primary);
        }
      }

      .el-icon {
        font-size: 20px;
        margin-right: tokens.$spacing-3;
        transition: all tokens.$duration-base;
      }

      span {
        position: relative;
        z-index: 1;
      }
    }
  }
}

/* 顶部栏 - 增强版 */
.layout-header {
  @include tokens.glassmorphism(0.8, 10px);
  background: var(--card-bg);
  box-shadow: tokens.$shadow-md;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 tokens.$spacing-6;
  transition: all tokens.$duration-base;
  position: relative;
  z-index: 10;
  border-bottom: 1px solid rgba(tokens.$brand-primary, 0.1);

  // 添加微光效果
  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: -100%;
    width: 100%;
    height: 1px;
    background: linear-gradient(
            90deg,
            transparent,
            tokens.$brand-primary,
            transparent
    );
    animation: shimmer 8s infinite;
  }

  &::after {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 1px;
    background: linear-gradient(
            90deg,
            transparent,
            rgba(tokens.$brand-primary, 0.5),
            transparent
    );
  }

  @keyframes shimmer {
    to {
      left: 100%;
    }
  }

  .header-left {
    h3 {
      color: var(--text-primary);
      font-size: tokens.$font-size-xl;
      font-weight: tokens.$font-weight-semibold;
      margin: 0;
      display: flex;
      align-items: center;
      gap: tokens.$spacing-2;

      &::before {
        content: '';
        width: 4px;
        height: 24px;
        background: tokens.$brand-primary;
        border-radius: tokens.$radius-sm;
      }
    }
  }

  .header-right {
    display: flex;
    align-items: center;
    gap: 16px;

    .system-status {
      .el-tag {
        padding: 6px 16px;
        font-weight: 500;
        border-radius: 20px;

        &.el-tag--success {
          @include tokens.gradient-bg(tokens.$color-success, tokens.$color-success-dark);
          border: none;
          color: white;
          box-shadow: 0 2px 8px rgba(tokens.$color-success, 0.3);
        }

        &.el-tag--danger {
          @include tokens.gradient-bg(tokens.$color-danger, tokens.$color-danger-dark);
          border: none;
          color: white;
          box-shadow: 0 2px 8px rgba(tokens.$color-danger, 0.3);
        }

        &.el-tag--info {
          background: rgba(tokens.$color-info, 0.1);
          border: 1px solid rgba(tokens.$color-info, 0.3);
          color: tokens.$color-info;
        }
      }

      .status-indicator {
        margin-right: tokens.$spacing-2;
        font-size: 12px;
        vertical-align: middle;

        &.breathing {
          @include tokens.breathing-animation;
        }
      }
    }

    .el-button-group {
      .el-button {
        border-radius: 8px;
        font-weight: 500;

        &:first-child {
          border-top-right-radius: 0;
          border-bottom-right-radius: 0;
        }

        &:last-child {
          border-top-left-radius: 0;
          border-bottom-left-radius: 0;
        }
      }
    }

    .el-switch {
      --el-switch-on-color: #{tokens.$brand-primary};

      :deep(.el-switch__core) {
        border-radius: tokens.$radius-full;
        box-shadow: tokens.$shadow-inner;
      }
    }
  }
}

/* 主内容区 */
.layout-main {
  background: var(--bg-color);
  padding: 0;
  overflow: auto;
  height: calc(100vh - 60px);
  position: relative;

  @include tokens.custom-scrollbar(12px, var(--bg-color), var(--border-color));
}

/* 页面过渡动画 */
.fade-enter-active,
.fade-leave-active {
  transition: all tokens.$duration-base tokens.$ease-out;
}

.fade-enter-from {
  opacity: 0;
  transform: translateX(20px);
}

.fade-leave-to {
  opacity: 0;
  transform: translateX(-20px);
}

/* 动画效果 */
@keyframes shimmer {
  to {
    left: 100%;
  }
}

/* 状态按钮组 */
.el-button-group {
  .el-button {
    &--success {
      &:hover:not(:disabled) {
        transform: translateY(-1px);
        box-shadow: tokens.$shadow-success;
      }
    }

    &--danger {
      &:hover:not(:disabled) {
        transform: translateY(-1px);
        box-shadow: tokens.$shadow-danger;
      }
    }

    &--warning {
      &:hover:not(:disabled) {
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(tokens.$color-warning, 0.4);
      }
    }
  }
}

/* 暗色主题 */
.dark {
  .layout-aside {
    background: linear-gradient(180deg, tokens.$dark-bg-tertiary 0%, tokens.$dark-bg-secondary 100%);

    &::before {
      background: radial-gradient(circle at top right, rgba(tokens.$brand-primary, 0.15) 0%, transparent 50%),
      radial-gradient(circle at bottom left, rgba(tokens.$brand-secondary, 0.15) 0%, transparent 50%);
    }

    .logo {
      background: rgba(0, 0, 0, 0.5);
      border-bottom-color: rgba(255, 255, 255, 0.05);
    }

    .el-menu-item {
      &.is-active {
        background: rgba(tokens.$brand-primary, 0.2);
      }
    }
  }

  .layout-header {
    box-shadow: 0 2px 16px rgba(0, 0, 0, 0.5);
    background: tokens.$dark-bg-elevated;

    &::after {
      background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.05), transparent);
    }
  }

  .layout-main {
    background: tokens.$dark-bg-primary;
  }
}

/* 响应式 */
@media (max-width: tokens.$breakpoint-md) {
  .layout-aside {
    width: 180px !important;

    .logo h2 {
      font-size: tokens.$font-size-lg;
    }

    .el-menu-item {
      height: 44px;
      line-height: 44px;
      margin: tokens.$spacing-1;

      .el-icon {
        font-size: 18px;
      }
    }
  }
  
  .layout-header {
    padding: 0 tokens.$spacing-4;
    
    .header-left h3 {
      font-size: tokens.$font-size-base;

      &::before {
        height: 20px;
      }
    }

    .header-right {
      gap: tokens.$spacing-2;

      .system-status {
        .el-tag {
          padding: tokens.$spacing-1 tokens.$spacing-2;
          font-size: tokens.$font-size-xs;
        }
      }
      
      .el-button {
        padding: tokens.$spacing-2 tokens.$spacing-3;
        font-size: tokens.$font-size-xs;
        height: 32px;
      }
    }
  }
}

/* 快捷键提示 */
.el-menu-item {
  position: relative;

  &[data-shortcut]::after {
    content: attr(data-shortcut);
    position: absolute;
    right: tokens.$spacing-4;
    top: 50%;
    transform: translateY(-50%);
    font-size: tokens.$font-size-xs;
    color: rgba(255, 255, 255, 0.4);
    background: rgba(0, 0, 0, 0.2);
    padding: 2px 6px;
    border-radius: tokens.$radius-sm;
    font-family: tokens.$font-mono;
  }
}
</style>

<style>
/* 自定义 ElLoading 样式 */
.deepsearch-loading {
  .el-loading-spinner {
    margin-top: -40px;
  }

  .el-loading-spinner .circular {
    width: 50px;
    height: 50px;
    animation: loading-rotate 2s linear infinite;
  }

  .el-loading-spinner .path {
    stroke: #409eff;
    stroke-width: 3;
    animation: loading-dash 1.5s ease-in-out infinite;
  }

  .el-loading-text {
    margin-top: 20px;
    font-size: 16px;
    color: #409eff;
    font-weight: 500;
    letter-spacing: 1px;
  }
}

@keyframes loading-rotate {
  100% {
    transform: rotate(360deg);
  }
}

@keyframes loading-dash {
  0% {
    stroke-dasharray: 1, 200;
    stroke-dashoffset: 0;
  }
  50% {
    stroke-dasharray: 90, 150;
    stroke-dashoffset: -40px;
  }
  100% {
    stroke-dasharray: 90, 150;
    stroke-dashoffset: -120px;
  }
}
</style>
