// deepsearch/webui/frontend/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <!-- 状态卡片 -->
    <el-row :gutter="20" class="status-cards">
      <el-col :md="6" :sm="12" :xs="24">
        <el-card class="status-card" shadow="hover">
          <div class="card-header">
            <el-icon class="card-icon" color="#409eff">
              <DataLine/>
            </el-icon>
            <span>处理事件</span>
          </div>
          <div class="card-value">{{ formatNumber(dashboardData.current?.total_events || 0) }}</div>
          <div v-if="dashboardData.trends?.events_change !== undefined" class="card-trend">
            <el-icon v-if="dashboardData.trends.events_change > 0" color="#67c23a">
              <Top/>
            </el-icon>
            <el-icon v-else-if="dashboardData.trends.events_change < 0" color="#f56c6c">
              <Bottom/>
            </el-icon>
            <span :class="getTrendClass(dashboardData.trends.events_change)">
              {{ Math.abs(dashboardData.trends.events_change) }}
            </span>
          </div>
        </el-card>
      </el-col>

      <el-col :md="6" :sm="12" :xs="24">
        <el-card class="status-card" shadow="hover">
          <div class="card-header">
            <el-icon class="card-icon" color="#67c23a">
              <CircleCheck/>
            </el-icon>
            <span>健康状态</span>
          </div>
          <div class="card-value">
            <el-tag :type="getHealthType(dashboardData.current?.health_status)" size="large">
              {{ getHealthText(dashboardData.current?.health_status) }}
            </el-tag>
          </div>
          <div class="card-trend">
            <!-- 占位元素，保持卡片高度一致 -->
            <span style="visibility: hidden;">占位</span>
          </div>
        </el-card>
      </el-col>

      <el-col :md="6" :sm="12" :xs="24">
        <el-card class="status-card" shadow="hover">
          <div class="card-header">
            <el-icon class="card-icon" color="#e6a23c">
              <Clock/>
            </el-icon>
            <span>队列大小</span>
          </div>
          <div class="card-value">{{ dashboardData.current?.queue_size || 0 }}</div>
          <div v-if="dashboardData.trends?.queue_size_change !== undefined" class="card-trend">
            <el-icon v-if="dashboardData.trends.queue_size_change > 0" color="#f56c6c">
              <Top/>
            </el-icon>
            <el-icon v-else-if="dashboardData.trends.queue_size_change < 0" color="#67c23a">
              <Bottom/>
            </el-icon>
            <span :class="getTrendClass(dashboardData.trends.queue_size_change, true)">
              {{ Math.abs(dashboardData.trends.queue_size_change) }}
            </span>
          </div>
        </el-card>
      </el-col>

      <el-col :md="6" :sm="12" :xs="24">
        <el-card class="status-card" shadow="hover">
          <div class="card-header">
            <el-icon class="card-icon" color="#f56c6c">
              <Warning/>
            </el-icon>
            <span>活跃告警</span>
          </div>
          <div class="card-value">{{ dashboardData.current?.active_alerts || 0 }}</div>
          <div class="card-trend">
            <!-- 占位元素，保持卡片高度一致 -->
            <span style="visibility: hidden;">占位</span>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 系统组件管理 -->
    <el-card class="components-card" shadow="hover">
      <template #header>
        <div class="card-header">
          <span>
            <el-icon><Setting/></el-icon>
            系统组件管理
          </span>
          <el-button :loading="componentLoading" size="small" @click="refreshComponents">
            <el-icon>
              <Refresh/>
            </el-icon>
            刷新
          </el-button>
        </div>
      </template>

      <el-table v-loading="componentLoading" :data="components" style="width: 100%">
        <el-table-column label="组件名称" prop="display_name" width="180"/>
        <el-table-column label="描述" min-width="200" prop="description"/>
        <el-table-column label="类型" prop="type" width="120">
          <template #default="scope">
            <el-tag :type="scope.row.type === 'infrastructure' ? 'primary' : 'success'" size="small">
              {{ scope.row.type === 'infrastructure' ? '基础设施' : '业务组件' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="状态" prop="status" width="120">
          <template #default="scope">
            <el-tag :type="getComponentStatusType(scope.row.status)" size="small">
              {{ getComponentStatusText(scope.row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column fixed="right" label="操作" width="180">
          <template #default="scope">
            <el-button
                v-if="scope.row.status !== 'running'"
                :disabled="!canStartComponent(scope.row)"
                size="small"
                type="primary"
                @click="handleStartComponent(scope.row)"
            >
              <el-icon>
                <VideoPlay/>
              </el-icon>
              启动
            </el-button>
            <el-button
                v-else
                :disabled="!canStopComponent(scope.row)"
                size="small"
                type="danger"
                @click="handleStopComponent(scope.row)"
            >
              <el-icon>
                <VideoPause/>
              </el-icon>
              停止
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-alert
          :closable="false"
          show-icon
          style="margin-top: 20px"
          type="info"
      >
        <template #title>
          温馨提示：基础设施组件已自动启动，业务组件需要手动启动。停止组件时，依赖该组件的其他组件也会被停止。
        </template>
      </el-alert>
    </el-card>

    <!-- 图表区域 -->
    <el-row :gutter="20" class="chart-area">
      <el-col :md="16" :xs="24">
        <el-card>
          <template #header>
            <div class="card-header">
              <span>事件处理趋势</span>
              <el-button-group size="small">
                <el-button :type="chartPeriod === '5m' ? 'primary' : ''" @click="changeChartPeriod('5m')">5分钟
                </el-button>
                <el-button :type="chartPeriod === '1h' ? 'primary' : ''" @click="changeChartPeriod('1h')">1小时
                </el-button>
                <el-button :type="chartPeriod === '24h' ? 'primary' : ''" @click="changeChartPeriod('24h')">24小时
                </el-button>
              </el-button-group>
            </div>
          </template>
          <div ref="trendChart" class="chart-container"></div>
        </el-card>
      </el-col>

      <el-col :md="8" :xs="24">
        <el-card>
          <template #header>
            <span>事件类型分布</span>
          </template>
          <div ref="pieChart" class="chart-container"></div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 告警列表 -->
    <el-card v-if="dashboardData.alerts?.length > 0" class="alerts-card">
      <template #header>
        <span>系统告警</span>
      </template>
      <el-timeline>
        <el-timeline-item
            v-for="(alert, index) in dashboardData.alerts"
            :key="index"
            :timestamp="formatTime(alert.timestamp)"
            :type="getAlertType(alert.level)"
            placement="top"
        >
          <el-alert
              :closable="false"
              :title="alert.message"
              :type="getAlertType(alert.level)"
              show-icon
          />
        </el-timeline-item>
      </el-timeline>
    </el-card>

    <!-- WebSocket 连接状态 -->
    <div class="ws-status">
      <el-tag :type="wsConnected ? 'success' : 'info'" size="small">
        <el-icon>
          <Link/>
        </el-icon>
        {{ wsConnected ? '实时连接' : '连接断开' }}
      </el-tag>
    </div>
  </div>
</template>

<script setup>
import {nextTick, onMounted, onUnmounted, ref, watch} from 'vue'
import {ElLoading, ElMessage, ElMessageBox} from 'element-plus'
import {
  Bottom,
  CircleCheck,
  Clock,
  DataLine,
  Link,
  Refresh,
  Setting,
  Top,
  VideoPause,
  VideoPlay,
  Warning
} from '@element-plus/icons-vue'
import * as echarts from 'echarts'
import dayjs from 'dayjs'
import {getDashboard, getRealtimeMetrics} from '@/api/monitor'
import {getAllComponents, startComponent, stopComponent} from '@/api/system'
import {wsManager} from '@/utils/websocket'
import {useSystemStore} from '@/stores/system'

// 系统状态
const systemStore = useSystemStore()

// 响应式数据
const dashboardData = ref({
  current: null,
  trends: null,
  alerts: []
})
const chartPeriod = ref('1h')
const wsConnected = ref(false)

// 组件管理相关
const components = ref([])
const componentLoading = ref(false)

// 图表实例
let trendChartInstance = null
let pieChartInstance = null

// 图表容器引用
const trendChart = ref(null)
const pieChart = ref(null)

// WebSocket 连接管理
const setupWebSocket = () => {
  // 监听连接状态变化
  const updateConnectionStatus = () => {
    const status = wsManager.getStatus()
    wsConnected.value = status.isConnected
  }

  // 设置事件处理器
  wsManager.on('open', () => {
    updateConnectionStatus()
    console.log('监控面板: WebSocket 已连接')
  })

  wsManager.on('message', (data) => {
    if (data.type === 'monitor_update') {
      dashboardData.value = data.data
      updateCharts()
    }
  })

  wsManager.on('close', () => {
    updateConnectionStatus()
  })

  wsManager.on('error', (error) => {
    // 静默处理错误，避免日志噪音
    updateConnectionStatus()
  })

  // 连接 WebSocket
  wsManager.connect()
}

// 初始化图表
const initCharts = () => {
  // 趋势图
  if (trendChart.value) {
    trendChartInstance = echarts.init(trendChart.value)
    trendChartInstance.setOption({
      tooltip: {
        trigger: 'axis',
        axisPointer: {
          type: 'cross'
        }
      },
      legend: {
        data: ['处理数', '成功率', '平均耗时']
      },
      grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
      },
      xAxis: {
        type: 'category',
        boundaryGap: false,
        data: []
      },
      yAxis: [
        {
          type: 'value',
          name: '处理数',
          position: 'left'
        },
        {
          type: 'value',
          name: '成功率 (%)',
          position: 'right',
          max: 100,
          min: 0
        }
      ],
      series: [
        {
          name: '处理数',
          type: 'line',
          data: [],
          smooth: true,
          itemStyle: {
            color: '#409eff'
          }
        },
        {
          name: '成功率',
          type: 'line',
          yAxisIndex: 1,
          data: [],
          smooth: true,
          itemStyle: {
            color: '#67c23a'
          }
        }
      ]
    })
  }

  // 饼图
  if (pieChart.value) {
    pieChartInstance = echarts.init(pieChart.value)
    pieChartInstance.setOption({
      tooltip: {
        trigger: 'item'
      },
      legend: {
        orient: 'vertical',
        left: 'left'
      },
      series: [
        {
          type: 'pie',
          radius: '50%',
          data: [],
          emphasis: {
            itemStyle: {
              shadowBlur: 10,
              shadowOffsetX: 0,
              shadowColor: 'rgba(0, 0, 0, 0.5)'
            }
          }
        }
      ]
    })
  }
}

// 更新图表数据
const updateCharts = async () => {
  try {
    const metrics = await getRealtimeMetrics()

    if (trendChartInstance && metrics.series) {
      const timestamps = metrics.timestamps?.map(t => dayjs(t).format('HH:mm:ss')) || []
      const series = []

      // 聚合所有事件类型的数据
      let totalCounts = []
      let avgSuccessRates = []

      Object.values(metrics.series).forEach(data => {
        if (data.count) {
          totalCounts = data.count
          avgSuccessRates = data.success_rate
        }
      })

      trendChartInstance.setOption({
        xAxis: {
          data: timestamps
        },
        series: [
          {
            name: '处理数',
            data: totalCounts
          },
          {
            name: '成功率',
            data: avgSuccessRates
          }
        ]
      })
    }

    // 更新饼图
    if (pieChartInstance && metrics.series) {
      const pieData = Object.entries(metrics.series).map(([name, data]) => ({
        name,
        value: data.count?.reduce((sum, val) => sum + val, 0) || 0
      }))

      pieChartInstance.setOption({
        series: [{
          data: pieData
        }]
      })
    }
  } catch (error) {
    console.error('更新图表失败:', error)
  }
}

// 格式化数字
const formatNumber = (num) => {
  if (num >= 1000000) {
    return (num / 1000000).toFixed(1) + 'M'
  } else if (num >= 1000) {
    return (num / 1000).toFixed(1) + 'K'
  }
  return num.toString()
}

// 格式化时间
const formatTime = (timestamp) => {
  return dayjs(timestamp).format('HH:mm:ss')
}

// 获取健康状态类型
const getHealthType = (status) => {
  const types = {
    'healthy': 'success',
    'degraded': 'warning',
    'unhealthy': 'danger'
  }
  return types[status] || 'info'
}

// 获取健康状态文本
const getHealthText = (status) => {
  const texts = {
    'healthy': '健康',
    'degraded': '降级',
    'unhealthy': '异常'
  }
  return texts[status] || '未知'
}

// 获取告警类型
const getAlertType = (level) => {
  const types = {
    'error': 'error',
    'warning': 'warning',
    'info': 'info'
  }
  return types[level] || 'info'
}

// 获取趋势类
const getTrendClass = (value, inverse = false) => {
  if (inverse) {
    return value > 0 ? 'trend-down' : 'trend-up'
  }
  return value > 0 ? 'trend-up' : 'trend-down'
}

// 获取初始数据
const fetchInitialData = async () => {
  try {
    dashboardData.value = await getDashboard(chartPeriod.value)
    await updateCharts()
    await refreshComponents()
  } catch (error) {
    ElMessage.error('获取仪表板数据失败')
  }
}

// 切换图表时间段
const changeChartPeriod = async (period) => {
  chartPeriod.value = period
  try {
    const loading = ElLoading.service({
      lock: true,
      text: '加载数据中...',
      background: 'rgba(0, 0, 0, 0.3)'
    })

    dashboardData.value = await getDashboard(period)
    await updateCharts()

    loading.close()
  } catch (error) {
    ElMessage.error('更新图表数据失败')
  }
}

// 刷新组件列表
const refreshComponents = async () => {
  componentLoading.value = true
  try {
    const res = await getAllComponents()
    // 转换成数组格式
    components.value = Object.entries(res.components || {}).map(([name, info]) => ({
      name,
      ...info
    }))
  } catch (error) {
    console.error('获取组件列表失败:', error)
    // 如果后端未启动，显示默认数据
    components.value = []
  } finally {
    componentLoading.value = false
  }
}

// 获取组件状态类型
const getComponentStatusType = (status) => {
  const types = {
    'running': 'success',
    'stopped': 'info',
    'initialized': 'warning',
    'uninitialized': '',
    'error': 'danger',
    'starting': 'warning',
    'stopping': 'warning'
  }
  return types[status] || ''
}

// 获取组件状态文本
const getComponentStatusText = (status) => {
  const texts = {
    'running': '运行中',
    'stopped': '已停止',
    'initialized': '已初始化',
    'uninitialized': '未初始化',
    'error': '错误',
    'starting': '正在启动',
    'stopping': '正在停止'
  }
  return texts[status] || status
}

// 判断是否可以启动组件
const canStartComponent = (component) => {
  // 检查依赖的组件是否都已启动
  if (component.dependencies && component.dependencies.length > 0) {
    for (const dep of component.dependencies) {
      const depComponent = components.value.find(c => c.name === dep)
      if (!depComponent || depComponent.status !== 'running') {
        return false
      }
    }
  }
  return true
}

// 判断是否可以停止组件
const canStopComponent = (component) => {
  // 基础设施组件通常不允许停止
  // 但我们允许停止，只是需要检查是否有其他组件依赖它
  const dependentComponents = components.value.filter(c =>
      c.dependencies && c.dependencies.includes(component.name) && c.status === 'running'
  )
  return dependentComponents.length === 0
}

// 启动组件
const handleStartComponent = async (component) => {
  let loading = null
  try {
    await ElMessageBox.confirm(
        `确定要启动组件 "${component.display_name}" 吗？`,
        '启动组件',
        {
          confirmButtonText: '确定',
          cancelButtonText: '取消',
          type: 'info'
        }
    )

    loading = ElLoading.service({
      lock: true,
      text: `正在启动 ${component.display_name}...`,
      background: 'rgba(0, 0, 0, 0.7)'
    })

    await startComponent(component.name)
    ElMessage.success(`组件 "${component.display_name}" 启动成功`)
    await refreshComponents()

  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(error.response?.data?.detail || '启动组件失败')
    }
  } finally {
    // 确保loading一定会被关闭
    if (loading) {
      loading.close()
    }
  }
}

// 停止组件
const handleStopComponent = async (component) => {
  let loading = null
  try {
    await ElMessageBox.confirm(
        `确定要停止组件 "${component.display_name}" 吗？`,
        '停止组件',
        {
          confirmButtonText: '确定',
          cancelButtonText: '取消',
          type: 'warning'
        }
    )

    loading = ElLoading.service({
      lock: true,
      text: `正在停止 ${component.display_name}...`,
      background: 'rgba(0, 0, 0, 0.7)'
    })

    await stopComponent(component.name)
    ElMessage.success(`组件 "${component.display_name}" 停止成功`)
    await refreshComponents()

  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(error.response?.data?.detail || '停止组件失败')
    }
  } finally {
    // 确保loading一定会被关闭
    if (loading) {
      loading.close()
    }
  }
}

// 处理窗口大小变化
const handleResize = () => {
  trendChartInstance?.resize()
  pieChartInstance?.resize()
}

// 监听系统状态变化
watch(() => systemStore.isRunning, (isRunning) => {
  if (isRunning) {
    // 引擎启动时，连接 WebSocket
    wsManager.shouldReconnect = true
    wsManager.connect()
  } else {
    // 引擎停止时，断开 WebSocket
    wsManager.shouldReconnect = false
    wsManager.disconnect()
    wsConnected.value = false
  }
})

onMounted(async () => {
  await fetchInitialData()
  await nextTick()
  initCharts()

  // 只有在引擎运行时才连接 WebSocket
  if (systemStore.isRunning) {
    setupWebSocket()
  }
  
  window.addEventListener('resize', handleResize)
})

onUnmounted(() => {
  // 组件卸载时断开 WebSocket
  wsManager.shouldReconnect = false
  wsManager.disconnect()
  
  trendChartInstance?.dispose()
  pieChartInstance?.dispose()
  window.removeEventListener('resize', handleResize)
})
</script>

<style lang="scss" scoped>
.dashboard {
  padding: 20px;
  background: var(--bg-color);
  min-height: 100vh;

  .status-cards {
    margin-bottom: 24px;

    .status-card {
      transition: all 0.3s ease;
      border-radius: 12px;
      overflow: hidden;
      position: relative;
      min-height: 160px; // 设置最小高度确保卡片大小一致

      // 确保内容垂直分布均匀
      :deep(.el-card__body) {
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
      }

      &::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        height: 4px;
        background: linear-gradient(90deg, var(--primary-color), var(--success-color));
        opacity: 0;
        transition: opacity 0.3s;
      }

      &:hover {
        transform: translateY(-4px);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);

        &::before {
          opacity: 1;
        }
      }

      .card-header {
        display: flex;
        align-items: center;
        margin-bottom: 16px;
        color: var(--text-secondary);
        font-size: 14px;
        font-weight: 500;

        .card-icon {
          font-size: 32px;
          margin-right: 12px;
          opacity: 0.9;
        }
      }

      .card-value {
        font-size: 32px;
        font-weight: 700;
        color: var(--text-primary);
        margin-bottom: 12px;
        letter-spacing: -1px;
      }

      .card-trend {
        display: flex;
        align-items: center;
        font-size: 14px;
        font-weight: 500;

        .el-icon {
          margin-right: 4px;
        }

        .trend-up {
          color: var(--success-color);
        }

        .trend-down {
          color: var(--danger-color);
        }
      }
    }
  }

  .chart-area {
    margin-bottom: 24px;

    .el-card {
      border-radius: 12px;

      .card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;

        h3 {
          margin: 0;
          font-size: 18px;
          font-weight: 600;
          color: var(--text-primary);
        }
      }
    }

    .chart-container {
      height: 380px;
      padding: 12px 0;
    }
  }

  .components-card {
    margin-bottom: 24px;
    border-radius: 12px;

    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;

      span {
        display: flex;
        align-items: center;
        font-size: 18px;
        font-weight: 600;
        color: var(--text-primary);

        .el-icon {
          margin-right: 8px;
          font-size: 20px;
        }
      }
    }

    .el-table {
      font-size: 14px;

      .el-table__row {
        transition: all 0.3s;

        &:hover {
          background-color: var(--bg-color);
        }
      }

      .component-status {
        display: flex;
        align-items: center;
        gap: 8px;

        .el-tag {
          font-weight: 500;
        }
      }
    }
  }

  .alerts-card {
    margin-bottom: 24px;
    border-radius: 12px;

    .el-timeline {
      padding: 16px 0;

      .el-timeline-item {
        padding-bottom: 24px;

        &:last-child {
          padding-bottom: 0;
        }
      }
    }
  }

  .ws-status {
    position: fixed;
    bottom: 24px;
    right: 24px;
    z-index: 999;

    .el-tag {
      padding: 8px 16px;
      font-weight: 500;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    }
  }
}

// 呼吸动画
@keyframes breathing {
  0%, 100% {
    opacity: 1;
    transform: scale(1);
  }
  50% {
    opacity: 0.6;
    transform: scale(1.2);
  }
}

.status-indicator {
  display: inline-block;
  margin-right: 4px;

  &.breathing {
    animation: breathing 2s ease-in-out infinite;
  }
}

// 暗色主题适配
.dark {
  .dashboard {
    background: var(--bg-color);

    .status-card {
      background: var(--card-bg);

      .card-value {
        color: var(--text-primary);
      }

      &:hover {
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);
      }
    }

    .el-card {
      background: var(--card-bg);
    }
  }
}

// 响应式
@media (max-width: 768px) {
  .dashboard {
    padding: 12px;

    .status-card {
      .card-header {
        .card-icon {
          font-size: 24px;
        }
      }

      .card-value {
        font-size: 24px;
      }
    }

    .chart-container {
      height: 300px;
    }
  }
}
</style>

// apps/web/.backup-cleanup/Dashboard/index.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import { Card, Row, Col, Button, Table, Alert, Timeline, Tag, message, Modal, Spin, Space, Typography } from 'antd'
import {
  ReloadOutlined,
  LinkOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  WarningOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  BarChartOutlined,
  DatabaseOutlined
} from '@ant-design/icons'
import * as echarts from 'echarts'
import dayjs from 'dayjs'
import { useSystemStore } from '@/stores/system'
import { useWebSocket } from '@/hooks/useWebSocket'
import StatusCard from '@/components/StatusCard'
import DataSourceCard from '@/components/DataSourceCard'
import CacheStatusCard from '@/components/CacheStatusCard'
import SystemAlerts from '@/components/SystemAlerts'
import { getDashboard, getRealtimeMetrics } from '@/services/monitor'
import { getAllComponents, startComponent, stopComponent } from '@/services/system'
import { throttle } from '@/utils/performance'
import type { ComponentStatus, DashboardData, SystemAlert } from '@/types'
import './index.scss'

const { Title, Text } = Typography

const Dashboard: React.FC = () => {
  // 状态管理
  const systemStore = useSystemStore()
  const [dashboardData, setDashboardData] = useState<DashboardData>({
    current: null,
    trends: null,
    alerts: []
  })
  const [chartPeriod, setChartPeriod] = useState('1h')
  const [loading, setLoading] = useState(false)
  const [componentLoading, setComponentLoading] = useState(false)
  const [lastUpdateTime, setLastUpdateTime] = useState<string>('')
  const [hasAlerts, setHasAlerts] = useState(false)
  const [components, setComponents] = useState<ComponentStatus[]>([])

  // 图表实例引用
  const trendChartRef = useRef<HTMLDivElement>(null)
  const pieChartRef = useRef<HTMLDivElement>(null)
  const trendChartInstance = useRef<echarts.ECharts | null>(null)
  const pieChartInstance = useRef<echarts.ECharts | null>(null)
  const resizeObserver = useRef<ResizeObserver | null>(null)

  // WebSocket连接
  const { connected: wsConnected, subscribe } = useWebSocket({
    url: process.env.REACT_APP_WS_URL || 'ws://localhost:8000/ws',
    onMessage: (data) => {
      if (data.type === 'monitor_update') {
        setDashboardData(data.data)
        updateCharts()
      }
    }
  })

  // 初始化图表
  const initCharts = useCallback(() => {
    // 趋势图
    if (trendChartRef.current && !trendChartInstance.current) {
      trendChartInstance.current = echarts.init(trendChartRef.current)

      // ResizeObserver监听
      if (window.ResizeObserver && !resizeObserver.current) {
        resizeObserver.current = new ResizeObserver(() => {
          trendChartInstance.current?.resize()
          pieChartInstance.current?.resize()
        })
        resizeObserver.current.observe(trendChartRef.current)
      }

      trendChartInstance.current.setOption({
        tooltip: {
          trigger: 'axis',
          axisPointer: { type: 'cross' }
        },
        legend: {
          data: ['处理数', '成功率']
        },
        grid: {
          left: '3%',
          right: '4%',
          bottom: '3%',
          containLabel: true
        },
        xAxis: {
          type: 'category',
          boundaryGap: false,
          data: []
        },
        yAxis: [
          {
            type: 'value',
            name: '处理数',
            position: 'left'
          },
          {
            type: 'value',
            name: '成功率 (%)',
            position: 'right',
            max: 100,
            min: 0
          }
        ],
        series: [
          {
            name: '处理数',
            type: 'line',
            data: [],
            smooth: true,
            itemStyle: { color: '#1890ff' }
          },
          {
            name: '成功率',
            type: 'line',
            yAxisIndex: 1,
            data: [],
            smooth: true,
            itemStyle: { color: '#52c41a' }
          }
        ]
      })
    }

    // 饼图
    if (pieChartRef.current && !pieChartInstance.current) {
      pieChartInstance.current = echarts.init(pieChartRef.current)
      pieChartInstance.current.setOption({
        tooltip: {
          trigger: 'item'
        },
        legend: {
          orient: 'vertical',
          left: 'left'
        },
        series: [
          {
            type: 'pie',
            radius: '50%',
            data: [],
            emphasis: {
              itemStyle: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
              }
            }
          }
        ]
      })
    }
  }, [])

  // 更新图表
  const updateCharts = async () => {
    try {
      const metrics = await getRealtimeMetrics()

      if (trendChartInstance.current && !trendChartInstance.current.isDisposed() && metrics.series) {
        const timestamps = metrics.timestamps?.map(t => dayjs(t).format('HH:mm:ss')) || []
        let totalCounts: number[] = []
        let avgSuccessRates: number[] = []

        Object.values(metrics.series).forEach((data: any) => {
          if (data.count) {
            totalCounts = data.count
            avgSuccessRates = data.success_rate
          }
        })

        trendChartInstance.current.setOption({
          xAxis: { data: timestamps },
          series: [
            { name: '处理数', data: totalCounts },
            { name: '成功率', data: avgSuccessRates }
          ]
        })
      }

      if (pieChartInstance.current && !pieChartInstance.current.isDisposed() && metrics.series) {
        const pieData = Object.entries(metrics.series).map(([name, data]: [string, any]) => ({
          name,
          value: data.count?.reduce((sum: number, val: number) => sum + val, 0) || 0
        }))

        pieChartInstance.current.setOption({
          series: [{ data: pieData }]
        })
      }
    } catch (error) {
      console.error('更新图表失败:', error)
    }
  }

  // 获取初始数据
  const fetchInitialData = async () => {
    setLoading(true)
    try {
      const data = await getDashboard(chartPeriod)
      setDashboardData(data)
      setHasAlerts(data.alerts && data.alerts.length > 0)
      setLastUpdateTime(new Date().toISOString())
      await updateCharts()
      await refreshComponents()
    } catch (error) {
      message.error('获取仪表板数据失败')
    } finally {
      setLoading(false)
    }
  }

  // 刷新组件列表
  const refreshComponents = async () => {
    setComponentLoading(true)
    try {
      const res = await getAllComponents()
      const componentList = Object.entries(res.components || {})
        .filter(([name]) => name !== 'webui')
        .map(([name, info]: [string, any]) => ({
          name,
          ...info
        }))
      setComponents(componentList)
      systemStore.updateComponents(componentList)
    } catch (error) {
      console.error('获取组件列表失败:', error)
      setComponents([])
      systemStore.updateComponents([])
    } finally {
      setComponentLoading(false)
    }
  }

  // 刷新全部数据（节流）
  const refreshAll = useCallback(
    throttle(async () => {
      setLoading(true)
      try {
        await Promise.all([
          fetchInitialData(),
          refreshComponents()
        ])
        setLastUpdateTime(new Date().toISOString())
        message.success('数据已刷新')
      } catch (error) {
        console.error('刷新失败:', error)
        message.error('刷新失败')
      } finally {
        setLoading(false)
      }
    }, 2000),
    [chartPeriod]
  )

  // 切换图表时间段
  const changeChartPeriod = async (period: string) => {
    setChartPeriod(period)
    try {
      const data = await getDashboard(period)
      setDashboardData(data)
      await updateCharts()
    } catch (error) {
      message.error('更新图表数据失败')
    }
  }

  // 启动组件
  const handleStartComponent = async (component: ComponentStatus) => {
    Modal.confirm({
      title: '启动组件',
      content: `确定要启动组件 "${component.display_name}" 吗？`,
      onOk: async () => {
        const hide = message.loading(`正在启动 ${component.display_name}...`, 0)
        try {
          await startComponent(component.name)
          message.success(`组件 "${component.display_name}" 启动成功`)
          await refreshComponents()
        } catch (error: any) {
          message.error(error.response?.data?.detail || '启动组件失败')
        } finally {
          hide()
        }
      }
    })
  }

  // 停止组件
  const handleStopComponent = async (component: ComponentStatus) => {
    Modal.confirm({
      title: '停止组件',
      content: `确定要停止组件 "${component.display_name}" 吗？`,
      type: 'warning',
      onOk: async () => {
        const hide = message.loading(`正在停止 ${component.display_name}...`, 0)
        try {
          await stopComponent(component.name)
          message.success(`组件 "${component.display_name}" 停止成功`)
          await refreshComponents()
        } catch (error: any) {
          message.error(error.response?.data?.detail || '停止组件失败')
        } finally {
          hide()
        }
      }
    })
  }

  // 工具函数
  const getHealthScore = () => {
    const status = dashboardData.current?.health_status
    const scoreMap: Record<string, number> = {
      'healthy': 100,
      'good': 100,
      'degraded': 75,
      'warning': 50,
      'unhealthy': 25,
      'error': 0
    }
    return scoreMap[status || ''] || 0
  }

  const getComponentStatusType = (status: string) => {
    const types: Record<string, string> = {
      'running': 'success',
      'stopped': 'default',
      'initialized': 'warning',
      'error': 'error',
      'starting': 'processing',
      'stopping': 'processing'
    }
    return types[status] || 'default'
  }

  const getComponentStatusText = (status: string) => {
    const texts: Record<string, string> = {
      'running': '运行中',
      'stopped': '已停止',
      'initialized': '已初始化',
      'uninitialized': '未初始化',
      'error': '错误',
      'starting': '正在启动',
      'stopping': '正在停止'
    }
    return texts[status] || status
  }

  // 组件表格列配置
  const columns = [
    {
      title: '组件名称',
      dataIndex: 'display_name',
      key: 'display_name',
      width: 180
    },
    {
      title: '描述',
      dataIndex: 'description',
      key: 'description',
      ellipsis: true
    },
    {
      title: '类型',
      dataIndex: 'type',
      key: 'type',
      width: 120,
      render: (type: string) => (
        <Tag color={type === 'infrastructure' ? 'blue' : 'green'}>
          {type === 'infrastructure' ? '基础设施' : '业务组件'}
        </Tag>
      )
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 180,
      render: (status: string, record: ComponentStatus) => (
        <Space>
          <Tag color={getComponentStatusType(status)}>
            {getComponentStatusText(status)}
          </Tag>
          {record.error_message && (
            <Text type="secondary" style={{ fontSize: 12 }}>
              {record.error_message}
            </Text>
          )}
        </Space>
      )
    },
    {
      title: '操作',
      key: 'action',
      width: 180,
      fixed: 'right' as const,
      render: (_: any, record: ComponentStatus) => (
        record.status !== 'running' ? (
          <Button
            type="primary"
            size="small"
            icon={<PlayCircleOutlined />}
            onClick={() => handleStartComponent(record)}
            disabled={record.dependencies?.some(dep =>
              components.find(c => c.name === dep)?.status !== 'running'
            )}
          >
            启动
          </Button>
        ) : (
          <Button
            danger
            size="small"
            icon={<PauseCircleOutlined />}
            onClick={() => handleStopComponent(record)}
            disabled={components.some(c =>
              c.dependencies?.includes(record.name) && c.status === 'running'
            )}
          >
            停止
          </Button>
        )
      )
    }
  ]

  // 生命周期
  useEffect(() => {
    fetchInitialData()

    // 延迟初始化图表
    const timer = setTimeout(() => {
      initCharts()
    }, 300)

    // 定时刷新
    const refreshTimer = setInterval(async () => {
      try {
        await refreshComponents()
        await systemStore.fetchStatus()
      } catch (error) {
        console.error('定时刷新失败:', error)
      }
    }, 30000)

    return () => {
      clearTimeout(timer)
      clearInterval(refreshTimer)
      resizeObserver.current?.disconnect()
      trendChartInstance.current?.dispose()
      pieChartInstance.current?.dispose()
    }
  }, [])

  // 监听WebSocket连接
  useEffect(() => {
    if (wsConnected) {
      subscribe(['monitor:update'])
    }
  }, [wsConnected, subscribe])

  return (
    <div className="dashboard">
      {/* 页面标题 */}
      <div className="page-header">
        <Title level={2}>监控仪表板</Title>
        <div className="header-actions">
          <Button
            type="primary"
            icon={<ReloadOutlined />}
            loading={loading}
            onClick={refreshAll}
          >
            刷新全部
          </Button>
          {lastUpdateTime && (
            <Text type="secondary" className="update-time">
              最后更新: {dayjs(lastUpdateTime).format('HH:mm:ss')}
            </Text>
          )}
        </div>
      </div>

      {/* 系统告警 */}
      {hasAlerts && <SystemAlerts alerts={dashboardData.alerts} />}

      {/* 状态卡片 */}
      <Row gutter={[24, 24]} className="status-cards">
        <Col xs={24} sm={12} md={6}>
          <StatusCard
            title="事件处理"
            value={dashboardData.current?.total_events || 0}
            unit="个"
            subtitle="累计处理"
            icon={<BarChartOutlined />}
            type="primary"
            progress={Math.min(100, ((dashboardData.current?.total_events || 0) / 10000) * 100)}
          />
        </Col>
        <Col xs={24} sm={12} md={6}>
          <StatusCard
            title="系统健康"
            value={getHealthScore()}
            unit="%"
            subtitle="所有组件运行状态"
            icon={<CheckCircleOutlined />}
            type={getHealthScore() >= 90 ? 'success' : getHealthScore() >= 70 ? 'warning' : 'danger'}
            progress={getHealthScore()}
          />
        </Col>
        <Col xs={24} sm={12} md={6}>
          <StatusCard
            title="事件队列"
            value={dashboardData.current?.queue_size || 0}
            unit="个"
            subtitle="当前积压"
            icon={<DatabaseOutlined />}
            type="warning"
            progress={Math.min(100, ((dashboardData.current?.queue_size || 0) / 1000) * 100)}
          />
        </Col>
        <Col xs={24} sm={12} md={6}>
          <StatusCard
            title="活跃告警"
            value={dashboardData.current?.active_alerts || 0}
            unit="个"
            subtitle="需要关注的问题"
            icon={<WarningOutlined />}
            type={dashboardData.current?.active_alerts ? 'danger' : 'success'}
            progress={Math.min(100, ((dashboardData.current?.active_alerts || 0) / 10) * 100)}
            pulse={dashboardData.current?.active_alerts > 0}
          />
        </Col>
      </Row>

      {/* 数据源和缓存状态 */}
      <Row gutter={[24, 24]} style={{ marginTop: 24 }}>
        <Col xs={24} md={12}>
          <DataSourceCard />
        </Col>
        <Col xs={24} md={12}>
          <CacheStatusCard />
        </Col>
      </Row>

      {/* 系统组件管理 */}
      <Card
        title="系统组件管理"
        className="components-card"
        extra={
          <Button
            size="small"
            shape="circle"
            icon={<ReloadOutlined />}
            onClick={refreshComponents}
          />
        }
      >
        <Spin spinning={componentLoading}>
          <Table
            dataSource={components}
            columns={columns}
            rowKey="name"
            pagination={false}
            scroll={{ x: 'max-content' }}
          />
        </Spin>
        <Alert
          message="温馨提示：基础设施组件已自动启动，业务组件需要手动启动。停止组件时，依赖该组件的其他组件也会被停止。"
          type="info"
          showIcon
          style={{ marginTop: 20 }}
        />
      </Card>

      {/* 图表区域 */}
      <Row gutter={[20, 20]} className="chart-area">
        <Col xs={24} md={16}>
          <Card title="实时趋势">
            <Space style={{ marginBottom: 16 }}>
              {['5m', '1h', '24h'].map(period => (
                <Button
                  key={period}
                  type={chartPeriod === period ? 'primary' : 'default'}
                  onClick={() => changeChartPeriod(period)}
                >
                  {period === '5m' ? '5分钟' : period === '1h' ? '1小时' : '24小时'}
                </Button>
              ))}
            </Space>
            <div ref={trendChartRef} className="chart-container" />
          </Card>
        </Col>
        <Col xs={24} md={8}>
          <Card title="事件类型分布">
            <div ref={pieChartRef} className="chart-container" />
          </Card>
        </Col>
      </Row>

      {/* 告警列表 */}
      {dashboardData.alerts?.length > 0 && (
        <Card title="系统告警" className="alerts-card">
          <Timeline>
            {dashboardData.alerts.map((alert: SystemAlert, index: number) => (
              <Timeline.Item
                key={index}
                color={alert.level === 'error' ? 'red' : alert.level === 'warning' ? 'orange' : 'blue'}
              >
                <Alert
                  message={alert.message}
                  type={alert.level as 'error' | 'warning' | 'info'}
                  showIcon
                  style={{ marginBottom: 8 }}
                />
                <Text type="secondary">{dayjs(alert.timestamp).format('HH:mm:ss')}</Text>
              </Timeline.Item>
            ))}
          </Timeline>
        </Card>
      )}

      {/* WebSocket 连接状态 */}
      <div className="ws-status">
        <Tag color={wsConnected ? 'success' : 'default'} icon={<LinkOutlined />}>
          {wsConnected ? '实时连接' : '连接断开'}
        </Tag>
      </div>
    </div>
  )
}

export default Dashboard
